url: https://mage.coach/
url-non: https://mage.coach
static-url: https://static.mage.coach

# Site settings
title: Mage Coach
name: Performance metrics report for Magento!
domain-name: Mage.coach
robots: INDEX,FOLLOW
email: hello@mage.coach
description: "How fast is your Magento site? How good does it follow web performance best practice rules? Find out by using Mage.coach."
google_analytics: //UA-31123279-1//unset

social:
  - title: twitter
    url: https://twitter.com/magecoach
  - title: facebook
    url: https://www.facebook.com/magecoach

# Build settings
markdown: kramdown
compress_html:
  clippings: all
  endings: all
kramdown:
    enable_coderay: false
    coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
permalink: pretty

sitemap:
  lastmod: 2016-09-26
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
